# Opciones de financiamiento para el proyecto

github: # Tu username de GitHub
patreon: # Tu username de Patreon
open_collective: # Tu nombre de Open Collective
ko_fi: # Tu username de Ko-fi
tidelift: # npm/nombre-paquete
community_bridge: # project-name
liberapay: # Tu username de Liberapay
issuehunt: # Tu username de IssueHunt
otechie: # Tu username de Otechie
lfx_crowdfunding: # project-name
custom: # URL personalizada para donaciones
