apiVersion: v1
kind: Secret
metadata:
  name: ciudad-robot-secrets
  namespace: ciudad-robot
type: Opaque
stringData:
  MONGO_PASSWORD: "robotcity"
  GRAFANA_PASSWORD: "ciudadrobot"
  JWT_SECRET: "cambiar-en-produccion"
